// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v01));
        
        string IMigrationMetadata.Id
        {
            get { return "201310010939344_v0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
