// <auto-generated />
namespace DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v03));
        
        string IMigrationMetadata.Id
        {
            get { return "201310161204377_v0.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
